package env

const SWARM_ENDPOINTS = "SWARM_ENDPOINTS"
const TLS = "TLS"
const TLS_CLIENT_KEY = "TLS_CLIENT_KEY"
const TLS_CLIENT_CERT = "TLS_CLIENT_CERT"
const CONNECT_CONTAINER_LABEL_VALUE = "CONNECT_CONTAINER_LABEL_VALUE"
const CONNECT_CONTAINER_NUMBER = "CONNECT_CONTAINER_NUMBER"
const TIME_INTERVAL_MS = "TIME_INTERVAL_MS"